version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app:cached
      - nuxt_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    tty: true
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
volumes:
  nuxt_node_modules: