version: '3.9'

services:
  web:
    container_name: taxi-stand-system-web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/web:cached
      - nuxt_node_modules:/web/node_modules
    ports:
      - "3000:3000"
    tty: true
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
volumes:
  nuxt_node_modules:
